---
title: "Rmarkdown üzerinde ödevleri nasıl hazırlayacağız?"
author: "Emrah Kırdök, Ph.D."

---

# Giriş

Dersler kapsamında verilecek ödevleri Rmarkdown üzerinde cevaplayacaksınız. Dolayısıyla, Rmarkdown bilgisi önem teşkil etmektedir. Bu belge, hem Rmarkdown ödevleri ile ilgili bir yol haritası çizmeyi hem de ileri seviye Rmarkdown ipuçlarını vermeyi hedeflemiştir.

## Dosya isimlendirme

Derslerin başında da bahsettiğimiz gibi, dosya isimlerinde İngilizce karakter seti dışında karakter ve boşluk kullanmayın! Bu kısım çok önemli, çünkü windows ve mac kodlama sistemi farklılıkları yüzünden ödevinizi açamayabilirim ve eksik puanlandırılırsınız.

Ödevlerinizi şu şekilde isimlendirmenizi tavsiye ederim:

> odev\_01\_emrah\_kirdok\_571.Rmd

> odev\_01\_emrah\_kirdok\_571.html

Dikkat ederseniz İngilizce karakter seti dışında karakter kullanmadım ve boşluk yerine alt çizgi "\_" (Shift tuşu + tire (-)) kullandım. 571 ise öğrenci numaram olsun. 

::: note

Eğer bu belgenin Rmarkdown versiyonunu inceliyorsanız, `_` karakteri önünde `\` işareti olduğunu göreceksiniz. Bu karakter kaçış karakteri (escape character) olarak isimlendirilir. Bu sayede Rmarkdown tarafından stil kodlarını normal metin olarak kullanabilirsiniz. Mesela `#` karakteri Rmakrdown için başlık olarak algılanıyor. Ancak siz bunu sadece normal bir karakter olarak kullanmak istiyorsanız `\#` yazabilirsiniz:

\#

:::

## Soru şekilleri

Sorular karşınıza bir paragraf olarak gelecektir. Aynı zamanda her sorunun sonunda, o sorunun puanı da olacaktır.

## Düz metin ile cevap verme

Soruların bazılarının cevabı normal metin olarak verilecektir. Bu durumda alıntı işareti kullanılarak cevabın verilmesi gereklidir. Mesela:

> Eğer sorulara normal metin olarak cevap vermeniz isteniyorsa, ">" karakterini kullanarak alıntı formatında cevabınızı veriniz.
> Belgenizi `html` formatına çevirdiğinizde, tam olarak bu şekilde bir biçimlendirme görmeniz gereklidir.

Kullanmanız gereken karakter aşağıda:

\>

## Kodlama ile verilecek cevaplar

Ödevlerinizin çoğunluğunda kod yazarak cevap vereceksiniz. Bu durumda aşağıdaki R kodu satırlarına bu cevabınızı R kodu olarak yazmanız gereklidir. 

```{r eval  = FALSE}
# Kodunuzu buraya yaziniz

```

Burada dikkat edilmesi gereken noktalar:

1. \# işareti ile başlayan satırlar R kodu olarak çalıştırılmaz. Bu kısımlar genelde okuyucuya bilgi vermek içindir
2. Kod bloklarında İngilizce karakter seti dışında karakter kullanmamaya özen gösterin.

::: tip

Kod yazarken \# işareti bir yorum belirtir. Yani \# işaretini gördüğünüz yerlerdeki kodlar çalıştırılmaz, sadece insanlar için bilgi verimesi için yazılır. 

Bu sayede yazdığınız programı okuyan bir araştırmacı, sadece yorum kısımlarına bakarak programınızda neler olduğunu anlayabilir.
:::

## Belgeyi derlemek

Cevaplarınızı düzgün bir şekilde verdikten sonra `knit` tuşuna basarak belgenizi `html` olarak derleyiniz ve bir sorun almadan düzgün bir çıktı aldığınızdan emin olunuz.
