# Önemli Konular {#sec-onemli}

R ve RStudio sistemleri üzerinde çalışırken bazı noktalara dikkat edilmesi gereklidir. Bu konulara dikkat ederseniz, daha verimli bir ders geçirebilirsiniz.

R sistemi, şu ana kadar çalıştığınız programlardan göre daha dik bir öğrenme eğrisine sahiptir. Ayrıca, R üzerinde çalışırken dikkat edilmesi gereken bazı noktalar bulunmaktadır. Aşağıdaki noktalara dikkat ederseniz, daha sorunsuz bir şekilde çalışabilirsiniz.

## Karakter kodlama sorunları

Bilgisayarlar geliştirildiği günden beri farklı karakter kodlama sistemlerini kullanırlar. Hatta farklı işletim sistemleri bile farklı karakter kodlama sistemleri ile çalışır. 

İlk geliştirilen kodlama sistemi olan [ASCII]() sadece belirli sayıda basılı karakter içerebiliyordu. Dolayısıyla, sadece belirli karakterleri kullanma imkanımız vardı.

Ancak ilerleyen yıllarda farklı kodlama sistemleri kullanıılmaya başlandı. Ancak ASCII karakter seti her zaman geriye doğru desteklendi. Yani, kodlama sistemleri değişse bile, ASCII karakterleri, aynı kodlarla belirtiliyordu.

Hepiniz farklı sistemler kullanıyoruz. DOlayısıyla bilgisayarlarımızın kodlama sistemlerinin uyuşmama ihtimalleri bulunmaktador. Mesela, son yıllarda gelişen UTF-8 kodlaması artık bütün dillerdeki karakterleri destekliyor, ancak Windows sistemleri hala UTF-8'i standart olarak kabul etmedi.

Dolayısıyla, gönderdiğiniz ödevleri düzgün bir şekilde görememe tehlikem bulunmaktadır Bu yüzden kodlamalarınızı sadece ASCII karakter seti üzerinden gerçekleştirin. Aslında çok kolay, aşağıdaki kutucukta bulunan harfler YASAK!

::: {.callout-important}

## Kullanılmaması gereken karakterler

Kodlama yaparken ve dosyaları isimlendirirken aşağıdaki karakterleri kullanmayınız:
```
Ö, Ç, Ş, İ, Ğ, Ü, Ş, ı, ü, ş, ç, ö 
```
Eğer sizin kullandığınız yerel dilinizde, İngilizce karakter seti dışında karakterler varsa, onları da kullanmayın!
:::
""
## Dosyaların isimlendirilmesi

Bir diğer önemli nokta ise dosyaların isimlendirilmesi. Dosya isimlerinde asla ASCII dışında karakter ve boşluk kullanmayın. 

::: {.callout-important}

## Dosya isimlerine dikkat ediniz

Dosya isimlerini seçerken asla ASCII dışında karakter ve boşluk kullanmayın. Eğer boşluk kullanmanız gerekirse "_" (alt çizgi, SHIFT ve - tuşlarına aynı anda basınız) karakterini kullanın.
:::

### Ondalık işareti

Türkiye ve Avrupa'da ondalık ayracı olarak `,` kulanılmaktadır. Mesela:

```
14,6
```

Ancak R programı, Amerika sistemini kullanır. Dolayısıyla ondalıklı sayılarla çalışmak istiyorsanız `.` işareti ile ondalık ayrımını gerçekleştirmeniz gerekir.

::: {.callout-note}
## Ondalık ayracı farklıdır

Peki kendi hazırladığınız verilerde ondalık ayracı olarak `,` kullanılmışsa ne olacak? İlerleyen bölümlerde, R içerisine veri yüklerken `dec` opsiyonu ilse ondalık ayracını seçmeyi öğreneceğiz.
:::
