# Pratik ve Uygulamalar

## Veri analizi

Vektörler uygulaması: 

+ [Boş Rmd dosyası](https://raw.githubusercontent.com/emrahkirdok/ybva/main/10-ekler/pratikler/vektorler.Rmd)
+ [Cevapları içeren Rmd dosyası]() YÜKLENMEDİ!

Vektörler, matrisler, veri çerçeveleri:

+ [Boş Rmd dosyası](https://raw.githubusercontent.com/emrahkirdok/ybva/main/10-ekler/pratikler/vektorler-matrisler-veri-cerceveleri.Rmd)
+ [Cevapları içeren Rmd dosyası](https://raw.githubusercontent.com/emrahkirdok/ybva/main/10-ekler/pratikler/cevaplar/vektorler-matrisler-veri-cerceveleri.Rmd)

Veri çerçeveleri:

+ [Boş Rmd dosyası](https://raw.githubusercontent.com/emrahkirdok/ybva/main/10-ekler/pratikler/veri-cerceveleri.Rmd)
+ [Cevapları içeren Rmd dosyası](https://raw.githubusercontent.com/emrahkirdok/ybva/main/10-ekler/pratikler/cevaplar/veri-cerceveleri.Rmd)

Veri okuma pratiği:

+ [Boş Rmd dosyası](https://raw.githubusercontent.com/emrahkirdok/ybva/main/10-ekler/pratikler/pratik-veri-okuma.Rmd)
+ [Cevapları içeren Rmd dosyası](https://raw.githubusercontent.com/emrahkirdok/ybva/main/10-ekler/pratikler/cevaplar/pratik-veri-okuma.Rmd)

Boston veri seti pratik:

+ [Boş Rmd dosyası](https://raw.githubusercontent.com/emrahkirdok/ybva/main/10-ekler/pratikler/boston.Rmd)
+ [Cevapları içeren Rmd dosyası](https://raw.githubusercontent.com/emrahkirdok/ybva/main/10-ekler/pratikler/cevaplar/boston-cevaplar.Rmd)

Gümüş ağacı veri seti pratik:

+ [Boş Rmd dosyası](https://raw.githubusercontent.com/emrahkirdok/ybva/main/10-ekler/pratikler/gumus-agaci.Rmd)
+ [Cevapları içeren Rmd dosyası](https://raw.githubusercontent.com/emrahkirdok/ybva/main/10-ekler/pratikler/cevaplar/gumus-agaci.Rmd)

Sınav veri seti pratiği:

+ [Boş Rmd dosyası](https://raw.githubusercontent.com/emrahkirdok/ybva/main/10-ekler/pratikler/sinav-veri-seti.Rmd)
+ [Cevapları içeren Rmd dosyası](https://raw.githubusercontent.com/emrahkirdok/ybva/main/10-ekler/pratikler/cevaplar/sinav-veri-seti.Rmd)

## Bilgisayarlı Düşünme

Abalone veri analizi ve doğrusal modeller:

+ [Boş Rmd dosyası](https://raw.githubusercontent.com/emrahkirdok/ybva/main/10-ekler/pratikler/bilgisayarli-dusunme-vize-2021-2022.Rmd)
+ [Cevapları içeren Rmd dosyası](https://raw.githubusercontent.com/emrahkirdok/ybva/main/10-ekler/pratikler/cevaplar/bilgisayarli-dusunme-vize-2021-2022.Rmd)

Amfibi veri seti çalışma. Boş kağıt yok.

+ [Pratik dosyası](https://raw.githubusercontent.com/emrahkirdok/ybva/main/10-ekler/pratikler/cevaplar/amphiBIO_calisma.Rmd)

Meme kanseri mikrodizin analizi:

+ [Boş Rmd dosyası](https://raw.githubusercontent.com/emrahkirdok/ybva/main/10-ekler/pratikler/bilgisayarli-dusunme-final-2023-2024.Rmd)
+ [Cevapları içeren Rmd dosyası](https://raw.githubusercontent.com/emrahkirdok/ybva/main/10-ekler/pratikler/cevaplar/bilgisayarli-dusunme-final-2023-2024.Rmd)